/**
 * scripts/gen-fn.js
 *
 * Run AFTER `npm run build` (Vite client + SSR builds).
 * Reads dist/client/index.html and writes a self-contained Netlify Function
 * at netlify/functions/ssr.mjs that:
 *   - imports the Vite SSR bundle (esbuild inlines it at Netlify build time)
 *   - embeds the HTML template as a string constant (no runtime fs reads)
 *   - handles every URL that doesn't match a static file
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

const template = readFileSync(resolve(root, 'dist/client/index.html'), 'utf-8')

mkdirSync(resolve(root, 'netlify/functions'), { recursive: true })

// The import path is relative from the generated function file's location:
//   netlify/functions/ssr.mjs → ../../dist/server/entry-server.js
// esbuild resolves and inlines this import at Netlify build time, so
// there are no runtime path lookups — everything ends up in one bundle.
const source = `// Auto-generated by scripts/gen-fn.js — do not edit manually.
// Re-generated every time \`npm run build:netlify\` runs.
import { render } from '../../dist/server/entry-server.js'

const TEMPLATE = ${JSON.stringify(template)}

export const handler = async (event) => {
  try {
    const qs = event.rawQuery ? '?' + event.rawQuery : ''
    const url = event.path + qs

    const { html, head } = await render(url)

    const body = TEMPLATE
      .replace('<!--app-head-->', head ?? '')
      .replace('<!--app-html-->', html)

    return {
      statusCode: 200,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
      body,
    }
  } catch (err) {
    console.error('[SSR Error]', err)
    return {
      statusCode: 500,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
      body: '<h1>500 — Internal Server Error</h1>',
    }
  }
}
`

writeFileSync(resolve(root, 'netlify/functions/ssr.mjs'), source)
console.log('✓  netlify/functions/ssr.mjs generated')
